// An object that know all the ALLOWED ACTION TYPES
// ~ contract or standard
const ActionTypes = {
  // Category
  CATEGORIES_ALL_REQ: "CATEGORIES_ALL_REQ",
  CATEGORIES_ALL_OK: "CATEGORIES_ALL_OK",
  CATEGORIES_ALL_X: "CATEGORIES_ALL_X",

  CATEGORY_ADD_REQ: "CATEGORY_ADD_REQ",
  CATEGORY_ADD_OK: "CATEGORY_ADD_OK",
  CATEGORY_ADD_X: "CATEGORY_ADD_X",

  CATEGORY_DELETE_REQ: "CATEGORY_DELETE_REQ",
  CATEGORY_DELETE_OK: "CATEGORY_DELETE_OK",
  CATEGORY_DELETE_X: "CATEGORY_DELETE_X",

  CATEGORY_GETBYID_REQ: "CATEGORY_GETBYID_REQ",
  CATEGORY_GETBYID_OK: "CATEGORY_GETBYID_OK",
  CATEGORY_GETBYID_X: "CATEGORY_GETBYID_X",

  CATEGORY_UPDATE_REQ: "CATEGORY_UPDATE_REQ",
  CATEGORY_UPDATE_OK: "CATEGORY_UPDATE_OK",
  CATEGORY_UPDATE_X: "CATEGORY_UPDATE_X",

  //CATEGORY_RANDOMIZED_REQ:   'CATEGORY_RANDOMIZED_REQ',
  //CATEGORY_RANDOMIZED_OK:    'CATEGORY_RANDOMIZED_OK',
  //CATEGORY_RANDOMIZED_X:     'CATEGORY_RANDOMIZED_X',

  //CATEGORY_CURRENT_RESET:    'CATEGORY_CURRENT_RESET',

  MEMBER_ALL_REQ: "MEMBER_ALL_REQ",
  MEMBER_ALL_OK: "MEMBER_ALL_OK",
  MEMBER_ALL_X: "MEMBER_ALL_X",

  MEMBER_ADD_REQ: "MEMBER_ADD_REQ",
  MEMBER_ADD_OK: "MEMBER_ADD_OK",
  MEMBER_ADD_X: "MEMBER_ADD_X",

  MEMBER_DELETE_REQ: "MEMBER_DELETE_REQ",
  MEMBER_DELETE_OK: "MEMBER_DELETE_OK",
  MEMBER_DELETE_X: "CATEGORY_DELETE_X",

  MEMBER_GETBYID_REQ: "MEMBER_GETBYID_REQ",
  MEMBER_GETBYID_OK: "MEMBER_GETBYID_OK",
  MEMBER_GETBYID_X: "MEMBER_GETBYID_X",

  MEMBER_UPDATE_REQ: "MEMBER_UPDATE_REQ",
  MEMBER_UPDATE_OK: "MEMBER_UPDATE_OK",
  MEMBER_UPDATE_X: "MEMBER_UPDATE_X"
};

export default ActionTypes;
